package NewLanguagePetar.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.ConstraintsFilteringSubstituteMenuPartDecorator;
import jetbrains.mps.lang.editor.menus.substitute.ReferenceScopeSubstituteMenuPart;
import jetbrains.mps.lang.editor.menus.ConceptMenusPart;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.editor.menus.substitute.DefaultSubstituteMenuLookup;
import jetbrains.mps.smodel.language.LanguageRegistry;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class StructureReference_SubstituteMenu extends SubstituteMenuBase {
  public StructureReference_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for StructureReference. Generated from implicit smart reference attribute.", new SNodePointer("r:68925f54-d194-4736-ad0d-fc03d0e4c77c(NewLanguagePetar.structure)", "3762182590348092918")));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new ConstraintsFilteringSubstituteMenuPartDecorator(new SMP_ReferenceScope_unqb9s_a(), CONCEPTS.StructureReference$sA));
    result.add(new SMP_Subconcepts_unqb9s_b());
    return result;
  }

  public class SMP_ReferenceScope_unqb9s_a extends ReferenceScopeSubstituteMenuPart {

    public SMP_ReferenceScope_unqb9s_a() {
      super(CONCEPTS.StructureReference$sA, LINKS.structureRef$Xr_9, new EditorMenuDescriptorBase("reference scope substitute menu part", null));
    }

  }
  public class SMP_Subconcepts_unqb9s_b extends ConceptMenusPart<SubstituteMenuItem, SubstituteMenuContext> {
    public SMP_Subconcepts_unqb9s_b() {
      super(new EditorMenuDescriptorBase("include menus for all the direct subconcepts of " + "StructureReference", null));
    }

    @Override
    protected Collection<SAbstractConcept> getConcepts(final SubstituteMenuContext _context) {
      return getDirectDescendants(_context, CONCEPTS.StructureReference$sA);
    }

    @Override
    protected Collection<SubstituteMenuItem> createItemsForConcept(SubstituteMenuContext context, SAbstractConcept concept) {
      return context.createItems(new DefaultSubstituteMenuLookup(LanguageRegistry.getInstance(context.getEditorContext().getRepository()), concept));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept StructureReference$sA = MetaAdapterFactory.getConcept(0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220ddb65f6L, "NewLanguagePetar.structure.StructureReference");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink structureRef$Xr_9 = MetaAdapterFactory.getReferenceLink(0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220ddb65f6L, 0x3435f5220ddb65f9L, "structureRef");
  }
}
