package NewLanguagePetar.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_DataType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_DataType() {
    super(0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220dd824eeL, "DataType", "r:68925f54-d194-4736-ad0d-fc03d0e4c77c(NewLanguagePetar.structure)/3762182590347879662");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_INTEGER_0 = new EnumerationDescriptor.MemberDescriptor("INTEGER", "INTEGER", 0x3435f5220dd824efL, "r:68925f54-d194-4736-ad0d-fc03d0e4c77c(NewLanguagePetar.structure)/3762182590347879663");
  private final EnumerationDescriptor.MemberDescriptor myMember_DECIMAL_0 = new EnumerationDescriptor.MemberDescriptor("DECIMAL", "DECIMAL", 0x3435f5220dd824f0L, "r:68925f54-d194-4736-ad0d-fc03d0e4c77c(NewLanguagePetar.structure)/3762182590347879664");
  private final EnumerationDescriptor.MemberDescriptor myMember_BOOLEAN_0 = new EnumerationDescriptor.MemberDescriptor("BOOLEAN", "BOOLEAN", 0x3435f5220dd82501L, "r:68925f54-d194-4736-ad0d-fc03d0e4c77c(NewLanguagePetar.structure)/3762182590347879681");
  private final EnumerationDescriptor.MemberDescriptor myMember_VARCHAR_0 = new EnumerationDescriptor.MemberDescriptor("VARCHAR", "VARCHAR", 0x3435f5220dd82505L, "r:68925f54-d194-4736-ad0d-fc03d0e4c77c(NewLanguagePetar.structure)/3762182590347879685");
  private final EnumerationDescriptor.MemberDescriptor myMember_DATE_0 = new EnumerationDescriptor.MemberDescriptor("DATE", "DATE", 0x3435f5220dd8250aL, "r:68925f54-d194-4736-ad0d-fc03d0e4c77c(NewLanguagePetar.structure)/3762182590347879690");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220dd824eeL, 0x3435f5220dd824efL, 0x3435f5220dd824f0L, 0x3435f5220dd82501L, 0x3435f5220dd82505L, 0x3435f5220dd8250aL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_INTEGER_0, myMember_DECIMAL_0, myMember_BOOLEAN_0, myMember_VARCHAR_0, myMember_DATE_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "INTEGER":
        return myMember_INTEGER_0;
      case "DECIMAL":
        return myMember_DECIMAL_0;
      case "BOOLEAN":
        return myMember_BOOLEAN_0;
      case "VARCHAR":
        return myMember_VARCHAR_0;
      case "DATE":
        return myMember_DATE_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
