package NewLanguagePetar.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAgregation = createDescriptorForAgregation();
  /*package*/ final ConceptDescriptor myConceptDomainInfo = createDescriptorForDomainInfo();
  /*package*/ final ConceptDescriptor myConceptDomainInstance = createDescriptorForDomainInstance();
  /*package*/ final ConceptDescriptor myConceptDomainTable = createDescriptorForDomainTable();
  /*package*/ final ConceptDescriptor myConceptExclusiveSpecialization = createDescriptorForExclusiveSpecialization();
  /*package*/ final ConceptDescriptor myConceptField = createDescriptorForField();
  /*package*/ final ConceptDescriptor myConceptNonExclusiveSpecialization = createDescriptorForNonExclusiveSpecialization();
  /*package*/ final ConceptDescriptor myConceptReference = createDescriptorForReference();
  /*package*/ final ConceptDescriptor myConceptSet = createDescriptorForSet();
  /*package*/ final ConceptDescriptor myConceptStructure = createDescriptorForStructure();
  /*package*/ final ConceptDescriptor myConceptStructureReference = createDescriptorForStructureReference();
  /*package*/ final ConceptDescriptor myConceptStructureRepository = createDescriptorForStructureRepository();
  /*package*/ final EnumerationDescriptor myEnumerationDataType = new EnumerationDescriptor_DataType();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAgregation, myConceptDomainInfo, myConceptDomainInstance, myConceptDomainTable, myConceptExclusiveSpecialization, myConceptField, myConceptNonExclusiveSpecialization, myConceptReference, myConceptSet, myConceptStructure, myConceptStructureReference, myConceptStructureRepository);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Agregation:
        return myConceptAgregation;
      case LanguageConceptSwitch.DomainInfo:
        return myConceptDomainInfo;
      case LanguageConceptSwitch.DomainInstance:
        return myConceptDomainInstance;
      case LanguageConceptSwitch.DomainTable:
        return myConceptDomainTable;
      case LanguageConceptSwitch.ExclusiveSpecialization:
        return myConceptExclusiveSpecialization;
      case LanguageConceptSwitch.Field:
        return myConceptField;
      case LanguageConceptSwitch.NonExclusiveSpecialization:
        return myConceptNonExclusiveSpecialization;
      case LanguageConceptSwitch.Reference:
        return myConceptReference;
      case LanguageConceptSwitch.Set:
        return myConceptSet;
      case LanguageConceptSwitch.Structure:
        return myConceptStructure;
      case LanguageConceptSwitch.StructureReference:
        return myConceptStructureReference;
      case LanguageConceptSwitch.StructureRepository:
        return myConceptStructureRepository;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationDataType);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAgregation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguagePetar", "Agregation", 0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220dd8262dL);
    b.class_(false, false, false);
    // extends: NewLanguagePetar.structure.Structure
    b.super_(0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220dd824c9L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:68925f54-d194-4736-ad0d-fc03d0e4c77c(NewLanguagePetar.structure)/3762182590347879981");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDomainInfo() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguagePetar", "DomainInfo", 0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220dd82510L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x2f16f1b357e19f43L);
    b.origin("r:68925f54-d194-4736-ad0d-fc03d0e4c77c(NewLanguagePetar.structure)/3762182590347879696");
    b.version(3);
    b.property("type", 0x3435f5220dd82520L).type(MetaIdFactory.dataTypeId(0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220dd824eeL)).origin("3762182590347879712").done();
    b.property("size", 0x3435f5220dd82522L).type(PrimitiveTypeId.STRING).origin("3762182590347879714").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDomainInstance() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguagePetar", "DomainInstance", 0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220dd82511L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:68925f54-d194-4736-ad0d-fc03d0e4c77c(NewLanguagePetar.structure)/3762182590347879697");
    b.version(3);
    b.aggregate("rowData", 0x3435f5220dd82515L).target(0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220dd824caL).optional(false).ordered(true).multiple(false).origin("3762182590347879701").done();
    b.aggregate("rowValue", 0x3435f5220dd82517L).target(0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220dd82510L).optional(false).ordered(true).multiple(false).origin("3762182590347879703").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDomainTable() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguagePetar", "DomainTable", 0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220dd82512L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:68925f54-d194-4736-ad0d-fc03d0e4c77c(NewLanguagePetar.structure)/3762182590347879698");
    b.version(3);
    b.aggregate("rows", 0x3435f5220dd82513L).target(0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220dd82511L).optional(true).ordered(true).multiple(true).origin("3762182590347879699").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForExclusiveSpecialization() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguagePetar", "ExclusiveSpecialization", 0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220dd8262eL);
    b.class_(false, false, false);
    // extends: NewLanguagePetar.structure.Structure
    b.super_(0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220dd824c9L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:68925f54-d194-4736-ad0d-fc03d0e4c77c(NewLanguagePetar.structure)/3762182590347879982");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguagePetar", "Field", 0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220dd8249bL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:68925f54-d194-4736-ad0d-fc03d0e4c77c(NewLanguagePetar.structure)/3762182590347879579");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNonExclusiveSpecialization() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguagePetar", "NonExclusiveSpecialization", 0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220dd8262fL);
    b.class_(false, false, false);
    // extends: NewLanguagePetar.structure.Structure
    b.super_(0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220dd824c9L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:68925f54-d194-4736-ad0d-fc03d0e4c77c(NewLanguagePetar.structure)/3762182590347879983");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguagePetar", "Reference", 0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220dd824caL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:68925f54-d194-4736-ad0d-fc03d0e4c77c(NewLanguagePetar.structure)/3762182590347879626");
    b.version(3);
    b.associate("reference", 0x3435f5220dd824cdL).target(0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220dd8249bL).optional(false).origin("3762182590347879629").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSet() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguagePetar", "Set", 0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220dd82630L);
    b.class_(false, false, false);
    // extends: NewLanguagePetar.structure.Structure
    b.super_(0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220dd824c9L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:68925f54-d194-4736-ad0d-fc03d0e4c77c(NewLanguagePetar.structure)/3762182590347879984");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStructure() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguagePetar", "Structure", 0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220dd824c9L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:68925f54-d194-4736-ad0d-fc03d0e4c77c(NewLanguagePetar.structure)/3762182590347879625");
    b.version(3);
    b.aggregate("fields", 0x3435f5220dd82616L).target(0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220dd8249bL).optional(true).ordered(true).multiple(true).origin("3762182590347879958").done();
    b.aggregate("table", 0x3435f5220dd82618L).target(0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220dd82512L).optional(false).ordered(true).multiple(false).origin("3762182590347879960").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStructureReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguagePetar", "StructureReference", 0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220ddb65f6L);
    b.class_(false, false, false);
    // extends: NewLanguagePetar.structure.Field
    b.super_(0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220dd8249bL);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:68925f54-d194-4736-ad0d-fc03d0e4c77c(NewLanguagePetar.structure)/3762182590348092918");
    b.version(3);
    b.associate("structureRef", 0x3435f5220ddb65f9L).target(0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220dd824c9L).optional(false).origin("3762182590348092921").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStructureRepository() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguagePetar", "StructureRepository", 0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220ddb661bL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:68925f54-d194-4736-ad0d-fc03d0e4c77c(NewLanguagePetar.structure)/3762182590348092955");
    b.version(3);
    b.aggregate("structures", 0x3435f5220ddb661cL).target(0x965ca885a8841e4L, 0xba571689a2e96932L, 0x3435f5220dd824c9L).optional(true).ordered(true).multiple(true).origin("3762182590348092956").done();
    return b.create();
  }
}
